# Generated by Django 3.2.8 on 2021-11-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERC721Token',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'ERC721 Token',
                'verbose_name_plural': 'ERC721 Tokens',
            },
        ),
        migrations.CreateModel(
            name='ERC721DefaultToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'ERC721 Default Token',
                'verbose_name_plural': 'ERC721 Default Tokens',
            },
        ),
        migrations.CreateModel(
            name='ERC20Token',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'ERC20 Token',
                'verbose_name_plural': 'ERC20 Tokens',
            },
        ),
        migrations.CreateModel(
            name='ERC20DefaultToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'ERC20 Default Token',
                'verbose_name_plural': 'ERC20 Default Tokens',
            },
        ),
    ]
